# See https://pre-commit.com/ for usage and config
repos:
  - repo: local
    hooks:
      - id: pylama
        name: pylama
        stages: [commit]
        language: system
        entry: .venv/bin/pylama
        types: [python]
      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: .venv/bin/pytest tests
        types: [python]
        pass_filenames: false
      - id: pytest-cov
        name: pytest
        stages: [push]
        language: system
        entry: pipenv run pytest --cov --cov-fail-under=0.5
        types: [python]
        pass_filenames: false
